# フリック設定
# キー番号,キーラベル,[[(K)]ポップアップラベル,[(N)]アクション],...

# キー番号は左上から 01234,56789,... で 19 まで
# キー番号のうしろに S を付けるとシフト時の設定

# キーラベルを設定しない場合は最初の 5 ラベルから合成

# ポップアップラベルとアクションは「あいうえお」段 5 つに加え、それぞれの
#「あ」左カーブ、「あ」右カーブ、「い」左カーブ、「い」右カーブ…… 15 個

# (K): カタカナのときだけ有効なポップアップラベルを指定 (「う」に濁点を付けず「ウ」には付けたいので)
# (N): 候補のあるモードでは一旦エンターを発行して確定してから続行 (特に x は操作キーなので)
# (n): 事前に n が残っている場合は何もせず、なければ n を発行してから続行 (nnn を回避)
# (Z): 全角モードでローマ字と解釈して出力 (整合性を保つわけでもないので Commit で代用できる)
# (Commit): このあとの文字列をローマ字として解釈せず直接出力
# (Comma): \, のようなエスケープは存在しないのでコンマはこれ

[JP]
10,(IconShift),SHIFT,(ToggleShift),,,CAPS,(Caps)
1,あ,あ,a,い,i,う,u,え,e,お,o,小,(N)xa,,,小,(N)xi,,,小,(N)xu,(K)゛,vu,小,(N)xe,,,小,(N)xo,,
2,か,か,ka,き,ki,く,ku,け,ke,こ,ko,,,゛,ga,,,゛,gi,,,゛,gu,,,゛,ge,,,゛,go
3,さ,さ,sa,し,si,す,su,せ,se,そ,so,,,゛,za,,,゛,zi,,,゛,zu,,,゛,ze,,,゛,zo
4,(IconBackspace),,(Backspace)
5,(IconLeft),＜,(DpadLeft),←,,↑,,→,,↓
5S,貼付,,(Paste)
6,た,た,ta,ち,ti,つ,tu,て,te,と,to,,,゛,da,,,゛,di,小,xtu,゛,du,,,゛,de,,,゛,do
7,な,な,na,に,ni,ぬ,nu,ね,ne,の,no
8,は,は,ha,ひ,hi,ふ,hu,へ,he,ほ,ho,゜,pa,゛,ba,゜,pi,゛,bi,゜,pu,゛,bu,゜,pe,゛,be,゜,po,゛,bo
9,(IconRight),＞,(DpadRight),←,,↑,,→,,↓
9S,Google,,(Google)
0,,カナ,q,：,:,10,(Num),＞,>,声,(Voice)
0S,,ｶﾅ,(HankakuKana),：,:,10,(Num),＞,>,声,(Voice)
11,ま,ま,ma,み,mi,む,mu,め,me,も,mo
12,や,や,ya,（,(,ゆ,yu,）,）,よ,yo,小,(N)xya,,,「,[,『,z[,小,(N)xyu,,,」,],』,z],小,(N)xyo
13,ら,ら,ra,り,ri,る,ru,れ,re,ろ,ro
14,(IconSpace),SPACE,(Space),,,Mush,(Mushroom)
14S,設定,,(Settings)
15,全角ａ\n☻abc記\nqwerty,abc,(Qwerty),絵☻,(Emoji),全角ａ,(Zenkaku),記号,(Symbol),qwerty,(Qwerty)
15S,全角ａ\n☻略記\nqwerty,abc,(Qwerty),絵☻,(Emoji),全角ａ,(Zenkaku),記号,(Symbol),qwerty,(Qwerty)
16,CXL\n ◻゙□゚ \n▽,◻゙□゚,(TransLast),◻゙,(DakutenLast),CXL,(Cancel),◻゚,(HandakutenLast),▽,(ShiftLast)
17,,わ,wa,を,wo,ん,nn,ー,-,～,~,小,(N)xwa
18,,、,(Comma),。,.,？,?,！,!,…,z.
18S,,□,(Z) ,（,(,「,[,）,),」,]
19,(IconReturn),,(Enter)

[Number]
10,(IconShift),SHIFT,(ToggleShift),,,CAPS,(Caps)
1,1,1,1
2,2,2,2
3,3,3,3
4,(IconBackspace),,(Backspace)
5,(IconLeft),＜,(DpadLeft),←,,↑,,→,,↓
6,4,4,4
7,5,5,5
8,6,6,6
9,(IconRight),＞,(DpadRight),←,,↑,,→,,↓
0,,かな,(Reset)
11,7,7,7
12,8,8,8
13,9,9,9
14,(IconSpace),SPACE,(Space),,,Mush,(Mushroom)
14S,設定,,(Settings)
15,全角ａ\n☻abc記\nqwerty,abc,(Qwerty),絵☻,(Emoji),全角ａ,(Zenkaku),記号,(Symbol),qwerty,(Qwerty)
15S,全角ａ\n☻略記\nqwerty,abc,(Qwerty),絵☻,(Emoji),全角ａ,(Zenkaku),記号,(Symbol),qwerty,(Qwerty)
16,＋\n￥＃＄\n＊,＃,#,￥,,＋,+,＄,$,＊,*,,,,,,,,,（,(,）,)
16S,＋\n＼＃＄\n×,＃,,＼,\,＋,+,＄,$,×,,,,,,,,,,（,(,）,)
17,0,0
18,－\n．，：\n／,，,(Commit)(Comma),．,(Commit).,－,(Commit)-,：,:,／,(Commit)/,,,,,,,,,｛,{,｝,}
18S,－\n．，：\n÷,，,,．,,－,,：,,÷,,,,,,,,,,｛,,｝
19,(IconReturn),,(Enter)

[Voice]
10,(IconShift),SHIFT,(ToggleShift),,,CAPS,(Caps)
2,声,,(Speech)
4,(IconBackspace),,(Backspace)
5,(IconLeft),＜,(DpadLeft),←,,↑,,→,,↓
6,、,,(Comma)
7,。,,.
9,(IconRight),＞,(DpadRight),←,,↑,,→,,↓
0,かな,,(Reset)
11,「,,[
12,」,,]
13,？,,?
14,(IconSpace),SPACE,(Space),,,Mush,(Mushroom)
14S,設定,,(Settings)
15,全角ａ\n☻abc記\nqwerty,abc,(Qwerty),絵☻,(Emoji),全角ａ,(Zenkaku),記号,(Symbol),qwerty,(Qwerty)
15S,全角ａ\n☻略記\nqwerty,abc,(Qwerty),絵☻,(Emoji),全角ａ,(Zenkaku),記号,(Symbol),qwerty,(Qwerty)
16,（,,(
17,）,,)
18,！,,!
19,(IconReturn),,(Enter)
