# Godan (simple) flick rule configuration
[Main]
10,(IconShift),SHIFT,(ToggleShift),,,CAPS,(Caps)
1,\nA\n1,A,a,あっ,axtu,あん,ann,ゃ,ya,1,1
2,Q\n KG\n2,K,k,＠,@,Q,q,G,g,2,2,,,,,□,z ,＾,^
3,,H,h,P,p,F,f,B,b,3,3
4,(IconBackspace),,(Backspace)
5,(IconLeft),＜,(DpadLeft),←,,↑,,→,,↓
6,\nI\n4,I,i,いっ,ixtu,いん,inn,ぃ,yi,4,4
7,I\n SZ\n5,S,s,＆,&,J,j,Z,z,5,5,,,,,％,%,＄,$
8,,M,m,／,/,L,l,ー,-,6,6,,,,,￥,,＼,\,,,〜,~,＿,_
9,(IconRight),＞,(DpadRight),←,,↑,,→,,↓
0,貼付\n：cxl＞\ngoogle,CXL,(Cancel),：,:,貼付,(Paste),＞,>,google,(Google)
11,\nU\n7,U,u,うっ,uxtu,うん,unn,ゅ,yu,7,7
12,C\n TD\n8,T,t,＋,+,C,c,D,d,8,8,,,,,＃,#,＊,*
13,,Y,y,（,(,X,(N)x,）,),9,9,＜,<,＞,>,［,(Commit)[,｛,{,,,,,］,(Commit)],｝,}
14,(IconSpace),SPACE,(Space),,,Mush,(Mushroom)
14S,設定,,(Settings)
15,^J\n☻Q記\n半ｶﾅ,Q,(Katakana),絵☻,(Emoji),^J,(Reset),記号,(Symbol),半ｶﾅ,(HankakuKana)
16,\nE\n,E,e,えっ,extu,えん,enn,ぇ,ye,00,00
17,\n：N・\n0,N,n,：,:,ん,(n)n,・,z/,0,0,,,,,；,;,＜,<,,,,,｜,|,＞,>
18,？\n。R！\n、,R,r,。,.,？,?,！,!,、,(Comma),,,,,…,z.,〜,~,,,,,↑,zk,↓,zj,→,zl,←,zh
19,(IconReturn),,(Enter)
20,L,L,(Ascii)
21,\nO\n,O,o,おっ,oxtu,おん,onn,ょ,yo,＇,',′,,｀,`
22,CXL\n ◻゙□゚ \n▽,◻゙□゚,(TransAuto),◻゙,(TransDakuten),CXL,(Cancel),◻゚,(TransHandakuten),▽,(TransShift)
23,V\n「W」\n,W,w,「,[,V,v,」,],＂,",,,,,『,z[,【,,,,,,』,z],】,,”,,“,

[ASCII]
10,(IconShift),SHIFT,(ToggleShift),,,CAPS,(Caps)
1,,A,a,,,,,,,1,1
2,,K,k,＠,@,Q,q,G,g,2,2,,,,,□,(Commit)　,＾,^
3,,H,h,P,p,F,f,B,b,3,3
4,(IconBackspace),,(Backspace)
5,(IconLeft),＜,(DpadLeft),←,,↑,,→,,↓
6,,I,i,,,,,,,4,4
7,,S,s,＆,&,J,j,Z,z,5,5,,,,,％,%,＄,$
8,,M,m,／,/,L,l,ー,-,6,6,,,,,￥,,＼,\,,,〜,~,＿,_
9,(IconRight),＞,(DpadRight),←,,↑,,→,,↓
0,貼付\n：cxl＞\ngoogle,CXL,(Cancel),：,:,貼付,(Paste),＞,>,google,(Google)
11,,U,u,,,,,,,7,7
12,,T,t,＋,+,C,c,D,d,8,8,,,,,＃,#,＊,*
13,,Y,y,（,(,X,x,）,),9,9,＜,<,＞,>,［,(Commit)[,｛,{,,,,,］,(Commit)],｝,}
14,(IconSpace),SPACE,(Space),,,Mush,(Mushroom)
14S,設定,,(Settings)
15,^J\n☻Q記\n半ｶﾅ,Q,(Katakana),絵☻,(Emoji),^J,(Reset),記号,(Symbol),半ｶﾅ,(HankakuKana)
16,,E,e,,,,,,,00,00
17,,N,n,：,:,,,・,z/,0,0,,,,,；,;,＜,<,,,,,｜,|,＞,>
18,？\n．R！\n，,R,r,．,.,？,?,！,!,，,(Comma),,,,,…,z.,〜,~,,,,,↑,,↓,,→,,←,
19,(IconReturn),,(Enter)
20,L,L,(Ascii)
21,,O,o,,,,,,,＇,',′,,｀,`
22,CXL\n ◻゙□゚ \n▽,◻゙□゚,(TransAuto),◻゙,(TransDakuten),CXL,(Cancel),◻゚,(TransHandakuten),▽,(TransShift)
23,,W,w,「,[,V,v,」,],＂,",,,,,『,,【,,,,,,』,,】,,”,,“,
