# Godan (simple) flick rule configuration
[JP]
10,(IconShift),SHIFT,(ShiftToggle),,,CAPS,(Caps)
1,\nA\n1,A,a,あっ,axtu,あん,ann,ゃ,ya,1,1
2,Q\n KG\n2,K,k,＠,@,Q,q,G,g,2,2,,,□,z ,＾,^
3,,H,h,P,p,F,f,B,b,3,3
4,(IconBackspace),,(Backspace)
5,(IconLeft),＜,(DpadLeft),←,,↑,,→,,↓
6,\nI\n4,I,i,いっ,ixtu,いん,inn,ぃ,yi,4,4
7,I\n SZ\n5,S,s,＆,&,J,j,Z,z,5,5,,,％,%,＄,$
8,,M,m,／,/,L,l,ー,-,6,6,,,￥,z ,＿,_,,,〜,~
9,(IconRight),＞,(DpadRight),←,,↑,,→,,↓
0,貼付\n：cxl＞\ngoogle,CXL,(Cancel),：,:,貼付,(Paste),＞,>,google,(Google)
11,\nU\n7,U,u,うっ,uxtu,うん,unn,ゅ,yu,7,7
12,C\n TD\n8,T,t,＋,+,C,c,D,d,8,8,,,＃,#,＊,*
13,,Y,y,（,(,X,x,）,）,9,9,＜,<,＞,>,［,z[,｛,z{,,,］,z],｝,z}
14,(IconSpace),SPACE,(Space),,,Mush,(Mushroom)
14S,設定,,(Settings)
15,^J\n☻Q記\n半ｶﾅ,Q,q,絵☻,(Emoji),^J,(Kana),記号,(Symbol),半ｶﾅ,(HankakuKana)
16,\nE\n,E,e,えっ,extu,えん,enn,ぇ,ye,00,00
17,\n：N・\n0,N,n,：,:,ん,(N)n,・,z/,0,0,,,；,;,＜,<,,,｜,|,＞,>
18,？\n。R！\n、,R,r,。,.,？,?,！,!,、,(Comma),,,…,... ,〜,~,,,↑,k,↓,j,→,l,←,h
19,(IconReturn),,(Enter)
20,L,L,(Qwerty)
21,\nO\n,O,o,おっ,oxtu,おん,onn,ょ,yo,',',′,,`,z`
22,CXL\n ◻゙□゚ \n▽,◻゙□゚,(TransLast),◻゙,(DakutenLast),CXL,(Cancel),◻゚,(HandakutenLast),▽,(ShiftLast)
23,V\n「W」\n,W,w,「,[,V,v,」,],＂,",,,『,z[,【,z[,,,』,z],】,z],”,,“,

[ASCII]
10,(IconShift),SHIFT,(ShiftToggle),,,CAPS,(Caps)
1,ん\nっAゃ\n1,A,a,あっ,axtu,あん,ann,ゃ,ya,1,1
2,,K,k,＠,@,Q,q,G,g,2,2,,,□,z ,＾,^
3,,H,h,P,p,F,f,B,b,3,3
4,(IconBackspace),,(Backspace)
5,(IconLeft),＜,(DpadLeft),←,,↑,,→,,↓
6,ん\nっIぃ\n4,I,i,いっ,ixtu,いん,inn,ぃ,yi,4,4
7,,S,s,＆,&,J,j,Z,z,5,5,,,％,%,＄,$
8,,M,m,／,/,L,l,ー,-,6,6,,,￥,z ,＿,_,,,〜,~
9,(IconRight),＞,(DpadRight),←,,↑,,→,,↓
0,貼付\n：cxl＞\ngoogle,CXL,(Cancel),：,:,貼付,(Paste),＞,>,google,(Google)
11,ん\nっUゅ\n7,U,u,うっ,uxtu,うん,unn,ゅ,yu,7,7
12,,T,t,＋,+,C,c,D,d,8,8,,,＃,#,＊,*
13,,Y,y,（,(,X,x,）,）,9,9,＜,<,＞,>,［,z[,｛,z{,,,］,z],｝,z}
14,(IconSpace),SPACE,(Space),,,Mush,(Mushroom)
14S,設定,,(Settings)
15,^J\n☻Q記\n半ｶﾅ,Q,q,絵☻,(Emoji),^J,(Kana),記号,(Symbol),半ｶﾅ,(HankakuKana)
16,ん\nっEぇ\n00,E,e,えっ,extu,えん,enn,ぇ,ye,00,00
17,,N,n,：,:,ん,(N)n,・,z/,0,0,,,；,;,＜,<,,,｜,|,＞,>
18,？\n。R！\n、,R,r,。,.,？,?,！,!,、,(Comma),,,…,... ,〜,~,,,↑,k,↓,j,→,l,←,h
19,(IconReturn),,(Enter)
20,L,L,(Qwerty)
21,ん\nっOょ\n＇,O,o,おっ,oxtu,おん,onn,ょ,yo,',',′,,`,z`
22,CXL\n ◻゙□゚ \n▽,◻゙□゚,(TransLast),◻゙,(DakutenLast),CXL,(Cancel),◻゚,(HandakutenLast),▽,(ShiftLast)
23,,W,w,「,[,V,v,」,],＂,",,,『,z[,【,z[,,,』,z],】,z],”,,“,
